package com.brousalis.mtm;

import com.brousalis.mtm.R;
 /*****************************************************\
 |           AUTO GEN FILE WARNING!!!                  |
 | !!! Edit this file ONLY in config/Config.java !!!   |
 | If you do modify this from within Eclipse your      |
 | changes WILL BE LOST!!!                             |
 \*****************************************************/
/**
 * This is the autogenerated config file. Do not edit it.
 */
public class Config
{
    public final static boolean LOGGING = false;
}